project_id = "cuxasxcurgnipbssnmeq"

[functions.mysql-api]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.redirect]
verify_jwt = false

[functions.links-api]
verify_jwt = false

[functions.payments-api]
verify_jwt = false

[functions.wallets-api]
verify_jwt = false

[functions.stats-api]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
